### ISSUE TITLE
Crashes in world loading

### ISSUE THREAD

**Issue by sm8925** [MoreMcmeta/core#107] opened 2024-11-17 21:45 UTC
**Describe the bug**
I'm not too sure the exact cause, but every time I try to load into a world it black screens and then crashes.

**To reproduce**
1. Open minecraft and launch as usual
2. load into any world
3. black screen except for chat and hotbar
4. crash

**Expected behavior**
I expected things to work normally and for it not to crash, but it did.

**Screenshots or videos**
Youtbe video: https://youtu.be/5ug7mUHFYNg?si=s498bjcRaFiiHjC0

**Which Minecraft versions does this bug affect?**
1.21

**Mod loader**
Which mod loaders does this bug affect?
Fabric 0.16.9

**Mods list**
What mods are you using?
About 767 mods
https://mclo.gs/rTisYBR (latest log because I am not gonna list out over 700 mods)

**Resource pack**
None

**Additional context**
I crash with exit code 255 and generates this crash log https://mclo.gs/Ly0KiWI  . I also asked chatgpt and it said smth about iris and sodium so maybe some sorta conflict with either of those two.

**Comment by soir20** [comment] 2024-11-17 23:10
This is a duplicate of https://github.com/MoreMcmeta/emissive-plugin/issues/29. Please update to emissive plugin 2.0.7, which fixes the issue.

I will move this to the emissive plugin repo since it's an issue specific to that mod.

**Closed** 2024-11-17 23:10 UTC
Labels: type: bug, status: duplicate, loader: forge, loader: fabric, mc: 1.21.x
