### ISSUE TITLE
MoreMcMeta & Embeddium Translucent Block Rendering Bug

### ISSUE THREAD

**Issue by Lonemind** [MoreMcmeta/core#55] opened 2023-11-25 01:46 UTC
**Describe the bug**
When MoreMcMeta is installed along with Embeddium blocks that are translucent like tall grass, sugar cane and glass do not render any other translucent blocks behind them. 

**Screenshots or videos**
https://imgur.com/a/Bjh4zhY

**Which Minecraft versions does this bug affect?**
1.18.2

**Mod loader**
Which mod loaders does this bug affect?
- [ ] Forge

**Mods list**
MoreMcMeta
Embeddium
EmbeddiumPlus
TexTrues Embeddium Options

**Resource pack**
n/a

**Comment by soir20** [comment] 2023-11-25 01:56
Are you using the emissive plugin? This looks like a duplicate of MoreMcmeta/emissive-plugin#6. I've investigated that issue previously, and it doesn't seem to be fixable in a way that would avoid breaking emissive plugin features. However, rendering changes in 1.19.2+ resolve the problem, if you are able to change MC versions.

**Comment by Lonemind** [comment] 2023-11-25 02:04
Ah, my apologies. I missed that post when I glanced through the closed list. And you are right, I am using the emissive plugin. I forgot to list it. My mistake.

Good to hear it's resolved in 1.19.2. I'm stuck in 1.18.2 for now. I'll suck it up and deal with it then. :P

Thank you for taking the time to respond and for doing so as quickly as you have. Cheers!

**Closed** 2023-11-25 02:05 UTC
Labels: type: bug
